mongodb/docs-visual-studio-extension

- snooty.toml
- source/builders.txt
- source/configuration.txt
- source/faq.txt
- source/index.txt
- source/install.txt
- source/linq.txt
- source/whats-new.txt
Add index page for the Visual Studio extension.
https://jira.mongodb.org/browse/DOCSP-19703
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61b7fceac52f2a460f564ba6
https://docs-mongodborg-staging.corp.mongodb.com/visual-studio-extension/docsworker-xlarge/DOCSP-19703-Index-Page/
The "TODO:" text in the page is intentional. These are items that I am not sure should be included yet, but must be fixed before the docs set is released to the public. If you feel these can and should be filled in now, let us know and we will work to get them resolved.
> (DOCSP-19703) Index Page

- source/whats-new.txt
Add "What's New" page
https://jira.mongodb.org/browse/DOCSP-19709
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61c0f10ec52f2a460f6a07a6
https://docs-mongodbcom-staging.corp.mongodb.com/visual-studio-extension/docsworker-xlarge/DOCSP-19709-Changelog/whats-new/
Note: This is almost a direct copy and paste of the [Kafka Version 1.0 Changelog](https://github.com/10gen/docs-kafka-connector/blob/v1.0/source/whats-new.txt)
> (DOCSP-19709) Changelog

- source/analyze-code.txt
- source/configuration.txt
- source/faq.txt
- source/index.txt
Change doc directives to ref.
https://jira.mongodb.org/browse/DOCSP-20214
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61d46eb041accb3633aa306a
[Index](https://docs-mongodbcom-staging.corp.mongodb.com/visual-studio-extension/docsworker-xlarge/DOCSP-20214-Remove-Doc/)
[Analyze Code](https://docs-mongodbcom-staging.corp.mongodb.com/visual-studio-extension/docsworker-xlarge/DOCSP-20214-Remove-Doc/analyze-code/)
[Configuration](https://docs-mongodbcom-staging.corp.mongodb.com/visual-studio-extension/docsworker-xlarge/DOCSP-20214-Remove-Doc/configuration/)
> (DOCSP-20214) Change :doc: to :ref:

- .github/workflows/checker.yml
- snooty.toml
This quotes a key in constants and adds a github action to run the checker utility.
N/A
N/A
https://docs-mongodborg-staging.corp.mongodb.com/golang/docsworker-xlarge/NNNNNNNNNNN/
> Add checker

- config/redirects
Update Redirect Versions
No ticket
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=61d8960441accb3633c37f36
[Not relevant, but here is the link](https://docs-mongodborg-staging.corp.mongodb.com/visual-studio-extension/docsworker-xlarge/update-redirect-versions/)
> Update Redirect Versions

- .github/pull_request_template.md
- README.md
- README.rst
- REVIEWING.md
> README and PR template update

- source/index.txt
- source/issues-and-help.txt
* DOCSP-20240: added issues and help page
* test
* DOCSP-20240: better introduction wording
* removing ds store files
JIRA - <https://jira.mongodb.org/browse/DOCSP-20240>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/visual-studio-extension/docsworker-xlarge/v1.0/>
> DOCSP-20240: added issues and help page v1.0 (#21)

- source/includes/error-list-window.rst
- source/index.txt
- source/known-issues.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26475
Staging - [Known issues page](https://docs-mongodbcom-staging.corp.mongodb.com/visual-studio-extension/docsworker-xlarge/DOCSP-26475-known-issues/known-issues/) | [Index/landing page](https://docs-mongodbcom-staging.corp.mongodb.com/visual-studio-extension/docsworker-xlarge/DOCSP-26475-known-issues/)
> DOCSP-26475: known issues

- source/includes/error-list-window.rst
- source/index.txt
- source/known-issues.txt
porting #32 to v1.0
staging:
https://docs-mongodbcom-staging.corp.mongodb.com/visual-studio-extension/docsworker-xlarge/v1.0/known-issues/
> porting #32 known issues to v1.0

- .github/.backportrc.json
- config/redirects
> version updates

- snooty.toml
- source/code-type/builders.txt
- source/code-type/linq.txt
- source/configuration.txt
- source/faq.txt
- source/includes/telemetry-data.rst
- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28133
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/visual-studio-extension/docsworker-xlarge/DOCSP-28133-link-new-docs/
> DOCSP-28133: link new c# docs

- source/known-issues.txt
JIRA - [DOCSP-28075](https://jira.mongodb.org/browse/DOCSP-28075)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/visual-studio-extension/docsworker-xlarge/DOCSP-28075-atlassearch-knownissue/known-issues/#partial-support-for-atlas-search-builders)
> DOCSP-28075: partial support for Search in known issues

- config/redirects
MUT output
Redirect 301 /docs/mongodb-analyzer/ https://www.mongodb.com/docs/mongodb-analyzer/current/
Redirect 301 /docs/mongodb-analyzer/master https://www.mongodb.com/docs/mongodb-analyzer/upcoming/
Redirect 301 /docs/mongodb-analyzer/v1.0/rules/ https://www.mongodb.com/docs/mongodb-analyzer/v1.0/
Redirect 301 /docs/mongodb-analyzer/v1.1/rules/ https://www.mongodb.com/docs/mongodb-analyzer/v1.1/
Redirect 301 /docs/mongodb-analyzer/v1.2/rules/ https://www.mongodb.com/docs/mongodb-analyzer/v1.2/
Redirect 301 /docs/mongodb-analyzer/master/rules/ https://www.mongodb.com/docs/mongodb-analyzer/master/
Redirect 301 /docs/mongodb-analyzer/current/rules/ https://www.mongodb.com/docs/mongodb-analyzer/current/
[PR Reviewing Guidelines](https://github.com/mongodb/docs-visual-studio-extension/blob/m …
> Redirect for current/rules

- config/redirects
- snooty.toml
- source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-32913
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/visual-studio-extension/docsworker-xlarge/docsp-32913-v1.3/whats-new/
> docsp-32913 - v1.3 release

- source/facets.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-32483>
Hey @mongoKart - here's the facets.toml file for MongoDB Analyzer.  Please merge if it looks good!
Thank you!
Sarah
> DOCSP-32483 programmatic tagging script for mongodb analyzer repo

- snooty.toml
Update driver constants to bring them in line with v1.3 and other docs
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/visual-studio-extension/docsworker-xlarge/rename-constants/
> update driver name

- source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-32948
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/visual-studio-extension/docsworker-xlarge/docsp-32948-fix-whats-new/whats-new/
> docsp-32948 - fix what's new items

- source/analyze-code.txt
- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44896
<li><a href=https://deploy-preview-68--mongodb-docs-csharp.netlify.app/analyze-code>analyze-code</a></li><li><a href=https://deploy-preview-68--mongodb-docs-csharp.netlify.app/index>index</a></li>
> DOCSP-44896 - TOC labels

- source/configuration.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46717>
At end of Options section: https://deploy-preview-71--docs-visual-studio-extension.netlify.app/configuration/#options
> DOCSP-46717 Source Code Link 404

- source/install.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-48228
<li><a href=https://deploy-preview-74--mongodb-docs-csharp.netlify.app/install>install</a></li>
> DOCSP-48228 - Remove H1

- snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-48302>
No pages to preview
> DOCSP-48302: Update snooty title

- source/configuration.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49582>
<li><a href=https://deploy-preview-80--docs-visual-studio-extension.netlify.app/configuration>configuration</a></li>
> [C# Analyzer] LinqVerbosity config option and IQueryable inference

- source/configuration.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49582>
<li><a href=https://deploy-preview-81--docs-visual-studio-extension.netlify.app/configuration>configuration</a></li>
> [C# Analyzer] Configuration Versioning Note

- config/redirects
- source/rules.txt
- source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-49735
<li><a href=https://deploy-preview-82--docs-visual-studio-extension.netlify.app/rules>rules</a></li><li><a href=https://deploy-preview-82--docs-visual-studio-extension.netlify.app/whats-new>whats-new</a></li>
> DOCSP-49735: C# driver 3.0 support

- source/analyze-code.txt
- source/code-type/builders.txt
- source/code-type/linq.txt
- source/code-type/pocos.txt
- source/configuration.txt
- source/faq.txt
- source/index.txt
- source/install.txt
- source/issues-and-help.txt
- source/known-issues.txt
- source/rules.txt
- source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-50081
> DOCSP-50081 Add noindex
